# Generated by Django 3.2.4 on 2023-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderListModel',
            fields=[
                ('orderListId', models.AutoField(primary_key=True, serialize=False)),
                ('orderIdList', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
