# Generated by Django 3.2.4 on 2023-01-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderManagement', '0001_initial'),
        ('ItemManagement', '0001_initial'),
        ('ProfileManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='buyerProfileIns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileManagement.buyerprofilemodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='itemIns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ItemManagement.itemmodel'),
        ),
        migrations.AddField(
            model_name='orderlistmodel',
            name='buyerProfileIns',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProfileManagement.buyerprofilemodel'),
        ),
    ]
