# Generated by Django 3.2.4 on 2022-12-28 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileManagement', '0003_auto_20221222_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('itemIdList', models.CharField(max_length=500)),
                ('buyerProfileModelIns', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProfileManagement.buyerprofilemodel')),
            ],
        ),
    ]
