# Generated by Django 3.2.4 on 2022-12-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfileModel',
            fields=[
                ('buyerProfileId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ProfileManagement.profilemodel')),
                ('cartId', models.IntegerField()),
                ('purchaseId', models.IntegerField()),
                ('orderId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfileModel',
            fields=[
                ('sellerProfileId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ProfileManagement.profilemodel')),
                ('storeName', models.CharField(max_length=50)),
            ],
        ),
    ]
