# Generated by Django 3.2.4 on 2023-01-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofilemodel',
            name='storeId',
        ),
        migrations.RemoveField(
            model_name='sellerprofilemodel',
            name='storeName',
        ),
    ]
