# Generated by Django 3.2.4 on 2022-12-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0002_buyerprofilemodel_sellerprofilemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerprofilemodel',
            old_name='orderId',
            new_name='orderListId',
        ),
        migrations.RenameField(
            model_name='buyerprofilemodel',
            old_name='purchaseId',
            new_name='purchaseListId',
        ),
    ]
