# Generated by Django 3.2.4 on 2023-02-15 15:39

import ItemManagement.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0002_auto_20230118_1729'),
        ('ItemManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='itemCategory',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='itemDetails',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='itemImage',
            field=models.ImageField(default='items/defaultItem.jpg', upload_to=ItemManagement.models.getDestinationImageUrl),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='sellerProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfileManagement.sellerprofilemodel'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='itemName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
