# Generated by Django 3.2.4 on 2023-01-18 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeId', models.AutoField(primary_key=True, serialize=False)),
                ('itemIdList', models.CharField(default='', max_length=500)),
                ('sellerProfileIns', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ProfileManagement.sellerprofilemodel')),
            ],
        ),
    ]
